version: "3"
version: "3"
services:
    test:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile
        ports:
            - "6655:6655"
        expose: ["3000"]
        volumes:
            - 
