on: [push, pull_request]

name: test
jobs:
  main:
    name: tftp (rust-${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
